---
title: Call with Christon
draft: true
---
Start: 4:14PM
End: 4:45PM


### Project:

- Set a deadline for our first email
- Create a website, and the automations to push to each platform.
- Focus in on persona, and focuses and format: monthly newsletters/articles?
    - Monthly goals, meet weekly on different ideas. Cycles of building and refining, building and refining. 
    - Follow the general structure: what is it, how did we get here, what does it mean, what can we do about it. 


- Christon wants to put out a “article” thing once a month which aligns with the following themes and principles:
    - Keeps personality, and is authentic to our view and voice.
    - Nothing’s sacred at this point either. Especially not business. The self-aggrandized business personas.
    - The king doesn’t have to be naked to look like a fucking idiot. 
  - The redefinition of norms in society at this point. 

- First article idea was inspired by advice he received at StationDC on cold emails and creating personal connection without any second-party reference/introduction:
    - Be as human as possible in your correspondence, especially in cold emails. Remember your audience, but be yourself.
    - Cold emails work if you’re trying to talk to someone very senior. A story example, a contact of Christon's sent a cold email to a CEO who really liked their "Chutzpah" and resume, and got invited to an all-women business roundtable/dinner event. This wouldn't have been possible without 1) the willingness to reach out, 2) pure-chance that another regular member of the roundtable/dinner event had to cancel last minute, and 3) the personal honesty, the desire to seek connection, and the poise/graciousness of their behavior.
    - Trivia: The first cold email was sent via the DoD’s email network ARPA-Net, and it resulted in $30M in sales.
    - Concept to be explored: The Nigerian Prince works for a reason.
    - Observation about our current zeitgeist: More people are looking for more human connection. The more colloquial Christon makes his emails, the more people respond.

# Project

- Christon is looking to create his own entity specifically for business writing where he’s very fed up with how overly technical most podcasts/writers make things more complicated than it needs to be.
  - There needs to be someone laughing from the back of the classroom. People are behaving like they’re in the papal congress, but this doesn’t jive in markets.
  - Executives are LLMs that hallucinate and spew LinkedIn speak. They apparently now have walk-out music. Make business boring again.
  - He wants to write this from a Colbert Report like persona for each of us that Sascha Barron Cohen. The Lifestyle optimizing business gurus. The Sascha Barron Cohen of Bloomberg.

- People enjoy the spectacle of the “grind-set” work life-style if only to keep people away from trying to repeat their own success. But all of this is falling apart in the face of LLMs. 

- Focus in on persona, and focuses and format: monthly newsletters/articles?
  - Monthly goals, meet weekly on different ideas. Cycles of building and refining, building and refining. 
  - Follow the general structure: what is it, how did we get here, what does it mean, what can we do about it. 

- Christon wants to put out a “article” thing, once a month. 
  - Keeps personality, and is authentic to our view and voice.
  - Nothing’s sacred at this point either. Especially not business. The self-aggrandized business personas.
  - The king doesn’t have to be naked to look like a fucking idiot. 

- The redefinition of norms in society at this point. 

# Inspiration

https://seobrien.com/university-tech-transfer


